### ISSUE TITLE
GUI item search bar is frozen

### ISSUE THREAD

**Issue by jordanasch** [elix-x/Excore#9]
I am having a problem with my GUI search bar, its stuck on a specific result. I can change it but it doesn't do anything to the item catalog, it just stays with the search results. I can still see the items in the catalog and get a recipe or uses for them its just like the search bar isn't connected to the catalog anymore.

You can see my search result stuck on water, it keeps the water catalog for each screenshot:
http://imgur.com/pD0kyfz.png
http://imgur.com/o3BYrhS.png
http://imgur.com/L92dN6Y.png

thanks for any help in advance!
Aschy

P.S. How do I delete the quick armor switching profiles on the left side?

**Comment by Elix-x** [comment]
First, which MC version are you on?
Second, this bug is more related to FEI rather than EXCore, isn't it?
And lastly, if you hover over any FEI element in gui and hold shift, it will draw help tooltip. For inventory saves, you should be able to shift+right click in order to delete one.

**Comment by jordanasch** [comment]
Hey Elix-x

Sorry I must have been tired I meant to post it to the FEI issue page!

I am on version 1.10.2

Would you prefer me to repost it on the FEI page?

**Comment by Elix-x** [comment]
Well, sadly i can no longer fix bugs for FEI 1.10.2.
And in any case, this is more of JEI bug because it can be noticed with JEI and without FEI installed (but please do not report it to mezz, i am pretty sure it was fixed already).
